In [8]:
import numpy as np
A=np.array([[2,4],[5,7]])
B=np.array([[4,6],[5,8]])

print("A ")

print(A)
print("  ")
print("B ")
print(B)


#Addition
print("Add")
C=A+B
print(C)
#SUBTRACTION
print("Sub")
C=A-B
print(C)

#MULTIPICATION
print("MUL")
C=A*B
print(C)


#MATRIX MULTIPICATION
print("Matrix Multiplication")
C=np.dot(A,B)
print(C)



#Transpose
print("Transpose")
A_Transpose=A.T
print(A_Transpose)




A 
[[2 4]
 [5 7]]
  
B 
[[4 6]
 [5 8]]
Add
[[ 6 10]
 [10 15]]
Sub
[[-2 -2]
 [ 0 -1]]
MUL
[[ 8 24]
 [25 56]]
Matrix Multiplication
[[28 44]
 [55 86]]
Transpose
[[2 5]
 [4 7]]


In [1]:
import numpy as np
# create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
# perform svd
U,S,VT=np.linalg.svd(X)
# choose the number of components to keep(eg,2)
n_components=2
# Reconstruct the matrix with reduced with reduced dimensions
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Orginal matrix :")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print(X_reconstructed)

Orginal matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
